/**
 * VibeContext Configuration Objects
 * 
 * Complete configuration for all five production styles, including
 * visual tokens, linguistic tone, AI parameters, and interaction patterns.
 */

import type { VibeContext } from '../types/vibe';

export const VIBE_CONFIGS: Record<string, VibeContext> = {
  VIRAL_NEON: {
    id: 'VIRAL_NEON',
    visualTokens: {
      bgColor: '#0A0A0A',
      primaryColor: '#8AFB17',
      accentColor: '#BF40BF',
      textColor: '#FFFFFF', // WCAG AA compliant (21:1 contrast on #0A0A0A)
      successColor: '#8AFB17', // Bright green for success
      warningColor: '#FFD700', // Gold/yellow for warnings
      errorColor: '#FF1744', // Bright red for errors
      infoColor: '#BF40BF', // Accent color for info
      headerFont: 'Inter Black Italic, sans-serif',
      bodyFont: 'Inter, sans-serif',
      borderRadius: '4px',
      animationStyle: 'snappy',
      cardStyle: {
        padding: '1.5rem',
        gap: '1rem',
        borderStyle: '2px solid var(--color-primary)',
        shadowStyle: '0 0 20px rgba(138, 251, 23, 0.3)',
      },
      spacing: {
        section: '3rem',
        component: '2rem',
        element: '1rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Send It',
        submitLoading: 'Generating...',
        cancel: 'Nah',
        start: 'Let\'s Go',
        startPerformance: 'Start the Show',
        join: 'Hop In',
        share: 'Drop Link',
        next: 'Next',
        back: 'Back',
        save: 'Lock It',
        edit: 'Fix It',
        delete: 'Yeet',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        goBack: 'Go Back',
        endScene: 'Wrap',
        exit: 'Exit',
        exportScript: 'Export Script',
        doAnother: 'Do Another',
        switchVibe: 'Switch Vibe',
        wrapPartyExit: 'End Session',
      },
      placeholders: {
        theme: 'What\'s the vibe? (10-200 chars)',
        plot: 'Drop the full lore, no cap (optional)...',
        jokes: 'Inside jokes, catchphrases, cursed lines (one per line)...',
        predefinedCharacterName: 'Character name (main character energy)',
        predefinedCharacterRole: 'Role / archetype (optional)',
        predefinedCharactersDescription:
          'Pre-define characters you want in the chaos. AI will fill the rest of the squad.',
        loadingCharactersBody: 'Cooking up unhinged characters with wild motivations...',
        loadingGeneratingBody: 'Writing the script and dripping visuals...',
        jokesCountLabel: 'custom lines locked in',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'This is required, no cap',
        invalid: 'That ain\'t it, chief',
        network: 'Connection failed, try again',
        generation: 'AI had a moment, retry?',
        sessionLoadFailed: 'Session couldn\'t be loaded. Double-check the code and try again.',
        wrapPartyUnavailable: 'Wrap Party isn\'t available because we lost track of your session. Rejoin from your link.',
      },
      successMessages: {
        saved: 'Locked in!',
        joined: 'You\'re in!',
        shared: 'Link dropped!',
        generated: 'It\'s ready!',
        wrapPartyReady: 'Performance wrapped! Time to vote and share.',
      },
      sectionTitles: {
        vibeSelection: 'Pick Your Vibe',
        configuration: 'The Vibe',
        castingCouch: 'The Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'The Squad',
        characters: 'The Cast',
        script: 'The Script',
        performance: 'The Stage',
        wrapParty: 'The Wrap',
        wrapPartySubtitle: 'Performance complete. Vote, meme, and send it to the group chat.',
        wrapPartyNotReady: 'Wrap Party isn\'t ready yet. Wait for the chaos to fully land.',
        wrapPartyDoAnotherConfirm: 'Do another with the same session?',
        wrapPartySwitchVibeConfirm: 'Switch vibe with the same session?',
        wrapPartyExitConfirm: 'End session for everyone?',
        shareComingSoon: 'Share — Coming soon',
        wrapPartyRejoinToVote: 'Rejoin with your name to vote.',
        chatReactionsComingSoon: 'Quick chat & reactions — Coming soon',
        wrapPartyTopIndicator: '🔥',
        joinSessionTitle: 'Join Session',
        loadingSession: 'Loading session...',
        redirectingToStage: 'Redirecting you to the stage...',
        redirectingToWrapParty: 'Redirecting you to the wrap party...',
        actorWelcomeTitle: 'Welcome to the cast',
        lockedAssignmentIntro: 'Your character assignment is locked in:',
        waitingForPerformance: 'Waiting for the director to start the performance...',
        waitingForGeneration: 'Waiting for the director to finish cooking the script and characters...',
        // Director form labels
        themeLabel: 'Theme',
        plotLabel: 'Deep Lore',
        toneLabel: 'Tone',
        participantsLabel: 'The Squad',
        chaosLevelLabel: 'Chaos Level',
        jokesLabel: 'Custom Lines',
        predefinedCharactersLabel: 'Pre-Defined Characters',
        // Loading titles
        loadingCharactersTitle: 'Generating Characters...',
        loadingContentTitle: 'Generating Content...',
        readThroughSubtext: 'Share your screen to walk through the script with everyone in the room.',
        readThroughConfirmTitle: 'Start read-through?',
        readThroughConfirmMessage: 'You\'ll go to the teleprompter. Share your screen so everyone can follow along. You can advance the script and end when done.',
        readThroughBanner: 'Read-through mode — share your screen so others can follow along.',
        endSceneConfirm: 'Wrap the Scene?',
        endSceneConfirmMessage: 'This will end the performance and move everyone to the wrap party.',
      },
    },
    aiParameters: {
      slangRegistry: [
        'no cap', 'fr fr', 'it\'s giving', 'slay', 'ate', 'period',
        'bestie', 'main character', 'vibe check', 'that\'s fire',
        'lowkey', 'highkey', 'bet', 'say less', 'facts', 'deadass',
      ],
      toneGuidelines: 'High-energy, meme-dense, chaotic, fast-paced dialogue with 2026 slang',
      pacing: 'snappy',
      archetypeLabels: {
        protagonist: 'The Main Character',
        antagonist: 'The Villain',
        sidekick: 'The Sidekick',
        comic: 'The Comedian',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 200,
      hoverEffects: 'glow',
      clickFeedback: 'pulse',
      soundEffects: ['click', 'whoosh'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Inter Black Italic" font-size="48" fill="#8AFB17" stroke="#BF40BF" stroke-width="0.5">SKITSO</text></svg>',
      typographyStyle: 'Inter Black Italic',
      animations: {
        glitch: true,
        pulse: true,
        scanlines: true,
      },
    },
  },
  INDIE_A24: {
    id: 'INDIE_A24',
    visualTokens: {
      bgColor: '#141414',
      primaryColor: '#CC7722',
      accentColor: '#FFFFFF',
      textColor: '#FFFFFF', // WCAG AA compliant (15.8:1 contrast on #141414)
      headerFont: 'EB Garamond, serif',
      bodyFont: 'Roboto Mono, monospace',
      borderRadius: '0px',
      animationStyle: 'slow-fade',
      cardStyle: {
        padding: '2rem',
        gap: '1.5rem',
        borderStyle: '1px solid rgba(204, 119, 34, 0.3)',
        shadowStyle: 'none',
      },
      spacing: {
        section: '4rem',
        component: '2.5rem',
        element: '1.25rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Submit',
        submitLoading: 'Generating...',
        cancel: 'Cancel',
        start: 'Begin',
        startPerformance: 'Begin Performance',
        join: 'Join',
        share: 'Share',
        next: 'Next',
        back: 'Back',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        goBack: 'Back',
        endScene: 'End Scene',
        exit: 'Exit',
        exportScript: 'Export Script',
        doAnother: 'Do Another',
        switchVibe: 'New Take',
        wrapPartyExit: 'End Session',
      },
      placeholders: {
        theme: 'Enter theme (10-200 characters)',
        plot: 'Optional: richer plot beats, motifs, or subtext...',
        jokes: 'Optional: specific lines or callbacks to weave into the script...',
        predefinedCharacterName: 'Character name',
        predefinedCharacterRole: 'Role / archetype (optional)',
        predefinedCharactersDescription:
          'Pre-define key characters; the AI will generate supporting roles to complete the ensemble.',
        loadingCharactersBody: 'Composing the cast with balanced, grounded archetypes...',
        loadingGeneratingBody: 'Writing the script and refining structure...',
        jokesCountLabel: 'custom lines added',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'This field is required',
        invalid: 'Invalid input',
        network: 'Connection error, please retry',
        generation: 'Generation failed, please retry',
        sessionLoadFailed: 'We couldn\'t load this session. Please verify the link or code.',
        wrapPartyUnavailable: 'Wrap Party is unavailable. Rejoin the session and try again.',
      },
      successMessages: {
        saved: 'Saved',
        joined: 'Joined successfully',
        shared: 'Shared',
        generated: 'Generated',
        wrapPartyReady: 'Performance complete. Time to debrief.',
      },
      sectionTitles: {
        vibeSelection: 'Select Production Style',
        configuration: 'Genre Selection',
        castingCouch: 'Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'Cast',
        characters: 'Characters',
        script: 'Script',
        performance: 'Performance',
        wrapParty: 'Wrap Party',
        wrapPartySubtitle: 'Performance complete. Share notes, favorites, and quiet applause.',
        wrapPartyNotReady: 'Wrap Party will unlock once the performance is complete.',
        wrapPartyDoAnotherConfirm: 'Do another with the same session?',
        wrapPartySwitchVibeConfirm: 'New take with the same session?',
        wrapPartyExitConfirm: 'End session for everyone?',
        shareComingSoon: 'Share — Coming soon',
        wrapPartyRejoinToVote: 'Rejoin with your name to vote.',
        chatReactionsComingSoon: 'Quick chat & reactions — Coming soon',
        wrapPartyTopIndicator: '✨',
        joinSessionTitle: 'Join Session',
        loadingSession: 'Loading session...',
        redirectingToStage: 'Redirecting to the stage...',
        redirectingToWrapParty: 'Redirecting to the wrap party...',
        actorWelcomeTitle: 'Welcome to the cast',
        lockedAssignmentIntro: 'Your character assignment is confirmed:',
        waitingForPerformance: 'Waiting for the director to begin the performance.',
        waitingForGeneration: 'Waiting for the director to finalize script and characters.',
        // Director form labels
        themeLabel: 'Theme',
        plotLabel: 'Plot',
        toneLabel: 'Tone',
        participantsLabel: 'Participants',
        chaosLevelLabel: 'Chaos Level',
        jokesLabel: 'Custom Lines',
        predefinedCharactersLabel: 'Pre-Defined Characters',
        // Loading titles
        loadingCharactersTitle: 'Generating Characters...',
        loadingContentTitle: 'Generating Content...',
        readThroughSubtext: 'Share your screen for a table read. Everyone in the room can follow along.',
        readThroughConfirmTitle: 'Begin read-through?',
        readThroughConfirmMessage: 'You\'ll go to the teleprompter. Share your screen so everyone can follow. Advance the script and end when you\'re done.',
        readThroughBanner: 'Read-through mode — share your screen so others can follow along.',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Cinematic, award-winning dialogue, contemplative, meaningful',
      pacing: 'contemplative',
      archetypeLabels: {
        protagonist: 'The Protagonist',
        antagonist: 'The Antagonist',
        sidekick: 'The Companion',
        comic: 'The Wit',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 500,
      hoverEffects: 'fade',
      clickFeedback: 'subtle',
      soundEffects: [],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="EB Garamond" font-size="42" fill="#CC7722" font-style="italic">SKITSO</text></svg>',
      typographyStyle: 'EB Garamond Italic',
      animations: {
        glitch: false,
        pulse: false,
        scanlines: false,
      },
    },
  },
  SITCOM_STUDIO: {
    id: 'SITCOM_STUDIO',
    visualTokens: {
      bgColor: '#F5F5F5',
      primaryColor: '#FF6B35',
      accentColor: '#004E89',
      textColor: '#000000', // WCAG AA compliant (18.1:1 contrast on #F5F5F5)
      successColor: '#4CAF50', // Classic green for success
      warningColor: '#FF9800', // Orange for warnings
      errorColor: '#F44336', // Red for errors
      infoColor: '#004E89', // Accent blue for info
      headerFont: 'Comic Sans MS, cursive',
      bodyFont: 'Arial, sans-serif',
      borderRadius: '12px',
      animationStyle: 'bouncy',
      cardStyle: {
        padding: '1.5rem',
        gap: '1rem',
        borderStyle: '3px solid var(--color-primary)',
        shadowStyle: '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      spacing: {
        section: '2.5rem',
        component: '1.5rem',
        element: '0.75rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Let\'s Do This!',
        submitLoading: 'Generating...',
        cancel: 'Never Mind',
        start: 'Action!',
        startPerformance: 'Lights, Camera, Action!',
        join: 'Join the Fun!',
        share: 'Share with Friends',
        next: 'Next →',
        back: '← Back',
        save: 'Save It',
        edit: 'Change It',
        delete: 'Remove',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        goBack: '← Back',
        endScene: 'That\'s a Wrap!',
        exit: 'Exit',
        exportScript: 'Export Script',
        doAnother: 'Do Another',
        switchVibe: 'Do Another',
        wrapPartyExit: 'End Session',
      },
      placeholders: {
        theme: 'What\'s the story? (10-200 chars)',
        plot: 'Optional: juicy plot beats, running gags, or big twists...',
        jokes: 'Throw in catchphrases or jokes (one per line)...',
        predefinedCharacterName: 'Character name',
        predefinedCharacterRole: 'Role on the show (optional)',
        predefinedCharactersDescription:
          'Pre-define regulars for this episode. The AI will add guest stars to match your cast size.',
        loadingCharactersBody: 'Casting the crew with sitcom-ready archetypes...',
        loadingGeneratingBody: 'Punching up jokes and building scenes...',
        jokesCountLabel: 'gags locked in',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'Oops! This is required',
        invalid: 'Hmm, that doesn\'t look right',
        network: 'Connection hiccup, try again',
        generation: 'Something went wrong, retry?',
        sessionLoadFailed: 'We couldn\'t find that session. Try the link again.',
        wrapPartyUnavailable: 'Wrap Party is taking a break. Rejoin from your session link.',
      },
      successMessages: {
        saved: 'All set!',
        joined: 'Welcome!',
        shared: 'Shared!',
        generated: 'Ready to go!',
        wrapPartyReady: 'That\'s a wrap! Time for curtain call.',
      },
      sectionTitles: {
        vibeSelection: 'Choose Your Style',
        configuration: 'The Setup',
        castingCouch: 'The Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'The Cast',
        characters: 'Characters',
        script: 'The Script',
        performance: 'Lights, Camera, Action!',
        wrapParty: 'That\'s a Wrap!',
        wrapPartySubtitle: 'The episode is over. Hand out awards and relive the best bits.',
        wrapPartyNotReady: 'Wrap Party opens once this episode officially ends.',
        wrapPartyDoAnotherConfirm: 'Do another with the same session?',
        wrapPartySwitchVibeConfirm: 'Do another episode with the same cast?',
        wrapPartyExitConfirm: 'End session for everyone?',
        shareComingSoon: 'Share — Coming soon',
        wrapPartyRejoinToVote: 'Rejoin with your name to vote.',
        chatReactionsComingSoon: 'Quick chat & reactions — Coming soon',
        wrapPartyTopIndicator: '🏆',
        joinSessionTitle: 'Join Session',
        loadingSession: 'Loading session...',
        redirectingToStage: 'Heading to the stage...',
        redirectingToWrapParty: 'Heading to the wrap party...',
        actorWelcomeTitle: 'Welcome to the show',
        lockedAssignmentIntro: 'Your role for this episode is locked:',
        waitingForPerformance: 'Waiting for the director to roll cameras.',
        waitingForGeneration: 'Waiting for the writer\'s room to finish the script.',
        // Director form labels
        themeLabel: 'Theme',
        plotLabel: 'Plot',
        toneLabel: 'Tone',
        participantsLabel: 'Cast Size',
        chaosLevelLabel: 'Chaos Level',
        jokesLabel: 'Jokes & Phrases',
        predefinedCharactersLabel: 'Pre-Defined Characters',
        // Loading titles
        loadingCharactersTitle: 'Generating Characters...',
        loadingContentTitle: 'Generating Content...',
        readThroughSubtext: 'Share your screen to walk through the episode with everyone in the room.',
        readThroughConfirmTitle: 'Start read-through?',
        readThroughConfirmMessage: 'You\'ll head to the teleprompter. Share your screen so the cast can follow along. Advance the script and call it when you\'re done.',
        readThroughBanner: 'Read-through mode — share your screen so others can follow along.',
        endSceneConfirm: 'That\'s a Wrap?',
        endSceneConfirmMessage: 'This will end the episode and move everyone to the wrap party.',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Nostalgic, high-energy, comedic, TV sitcom style',
      pacing: 'energetic',
      archetypeLabels: {
        protagonist: 'The Lead',
        antagonist: 'The Foil',
        sidekick: 'The Best Friend',
        comic: 'The Jokester',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 300,
      hoverEffects: 'bounce',
      clickFeedback: 'bounce',
      soundEffects: ['laugh', 'applause'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Comic Sans MS" font-size="44" fill="#FF6B35">SKITSO</text></svg>',
      typographyStyle: 'Comic Sans MS',
      animations: {
        glitch: false,
        pulse: true,
        scanlines: false,
      },
    },
  },
  BRAINROT_THEATER: {
    id: 'BRAINROT_THEATER',
    visualTokens: {
      bgColor: '#000000',
      primaryColor: '#FF00FF',
      accentColor: '#00FFFF',
      textColor: '#FFFFFF', // WCAG AA compliant (21:1 contrast on #000000)
      headerFont: 'Impact, sans-serif',
      bodyFont: 'Arial Black, sans-serif',
      borderRadius: '20px',
      animationStyle: 'bouncy',
      cardStyle: {
        padding: '2rem',
        gap: '1.5rem',
        borderStyle: '4px dashed var(--color-primary)',
        shadowStyle: '0 0 30px rgba(255, 0, 255, 0.5), 0 0 60px rgba(0, 255, 255, 0.3)',
      },
      spacing: {
        section: '2rem',
        component: '1.5rem',
        element: '1rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'SEND IT!!!',
        submitLoading: 'GENERATING...',
        cancel: 'NOPE',
        start: 'CHAOS MODE',
        startPerformance: 'START THE CHAOS!!!',
        join: 'JOIN THE CHAOS',
        share: 'SPREAD IT',
        next: 'NEXT →→→',
        back: '←←← BACK',
        save: 'LOCK IT IN',
        edit: 'FIX IT NOW',
        delete: 'DELETE FOREVER',
        pause: 'PAUSE',
        resume: 'RESUME',
        advance: 'ADVANCE',
        goBack: '←←← BACK',
        endScene: 'WRAP IT!!!',
        exit: 'EXIT',
        exportScript: 'EXPORT SCRIPT',
        doAnother: 'DO ANOTHER!!!',
        switchVibe: 'SWITCH VIBE!!!',
        wrapPartyExit: 'END SESSION',
      },
      placeholders: {
        theme: 'WHAT\'S THE CHAOS? (10-200 CHARS)',
        plot: 'OPTIONAL LORE DUMP / PROPHECY / FANFIC...',
        jokes: 'TYPE UNHINGED LINES OR MEMES (ONE PER LINE)...',
        predefinedCharacterName: 'CHARACTER NAME (MAKE IT CHAOTIC)',
        predefinedCharacterRole: 'ROLE / CHAOS JOB (OPTIONAL)',
        predefinedCharactersDescription:
          'LOCK IN ANY CHAOTIC OCs FIRST. AI WILL SPAWN MORE AGENTS OF CHAOS TO FILL THE CAST.',
        loadingCharactersBody: 'BREWING UNSTABLE CHARACTERS WITH MAXIMUM BRAINROT...',
        loadingGeneratingBody: 'WRITING SCRIPT + COOKING IMAGES AT THE SAME TIME. STAY SEATED.',
        jokesCountLabel: 'chaos lines locked',
        name: 'YOUR NAME',
        sessionCode: 'ENTER CODE',
        search: 'SEARCH...',
      },
      errorMessages: {
        required: 'YOU NEED THIS!!!',
        invalid: 'WRONG!!!',
        network: 'CONNECTION BROKE, RETRY?',
        generation: 'AI BROKE, RETRY?',
        sessionLoadFailed: 'SESSION NOT FOUND. CHECK THE CODE AND RUN IT BACK.',
        wrapPartyUnavailable: 'WRAP PARTY GLITCHED. REJOIN THE CHAOS AND TRY AGAIN.',
      },
      successMessages: {
        saved: 'LOCKED!!!',
        joined: 'YOU\'RE IN!!!',
        shared: 'SPREAD!!!',
        generated: 'READY!!!',
        wrapPartyReady: 'CHAOS COMPLETE!!! VOTE AND SCREAM!!!',
      },
      sectionTitles: {
        vibeSelection: 'PICK YOUR CHAOS',
        configuration: 'THE CHAOS',
        castingCouch: 'THE CASTING COUCH',
        characterDossier: 'CHARACTER DOSSIER',
        personalityTraits: 'PERSONALITY TRAITS',
        attributes: 'ATTRIBUTES',
        hiddenMotivation: 'HIDDEN MOTIVATION',
        participants: 'THE SQUAD',
        characters: 'THE CAST',
        script: 'THE SCRIPT',
        performance: 'THE STAGE',
        wrapParty: 'THE WRAP',
        wrapPartySubtitle: 'SHOW\'S OVER. TIME TO VOTE ON THE CHAOS.',
        wrapPartyNotReady: 'WRAP PARTY UNLOCKS AFTER THE FINAL SCENE.',
        wrapPartyDoAnotherConfirm: 'DO ANOTHER WITH THE SAME SESSION?',
        wrapPartySwitchVibeConfirm: 'SWITCH VIBE WITH SAME SESSION?!',
        wrapPartyExitConfirm: 'END SESSION FOR EVERYONE?',
        shareComingSoon: 'SHARE — COMING SOON',
        wrapPartyRejoinToVote: 'REJOIN WITH YOUR NAME TO VOTE.',
        chatReactionsComingSoon: 'QUICK CHAT & REACTIONS — COMING SOON',
        wrapPartyTopIndicator: '🤯',
        joinSessionTitle: 'JOIN THE CHAOS',
        loadingSession: 'LOADING SESSION...',
        redirectingToStage: 'SENDING YOU TO THE STAGE...',
        redirectingToWrapParty: 'SENDING YOU TO THE WRAP PARTY...',
        actorWelcomeTitle: 'WELCOME TO THE CHAOS',
        lockedAssignmentIntro: 'YOUR CHARACTER IS LOCKED. NO BACKSIES.',
        waitingForPerformance: 'WAITING FOR DIRECTOR TO UNLEASH THE PERFORMANCE...',
        waitingForGeneration: 'WAITING FOR THE AI TO FINISH COOKING THE SCRIPT + CAST...',
        // Director form labels
        themeLabel: 'THE PROMPT',
        plotLabel: 'DEEP LORE',
        toneLabel: 'VIBE',
        participantsLabel: 'THE SQUAD SIZE',
        chaosLevelLabel: 'CHAOS LEVEL',
        jokesLabel: 'CUSTOM CHAOS LINES',
        predefinedCharactersLabel: 'PRE-DEFINED CHAOS CHARACTERS',
        // Loading titles
        loadingCharactersTitle: 'GENERATING CHARACTERS...',
        loadingContentTitle: 'GENERATING CONTENT...',
        readThroughSubtext: 'SHARE YOUR SCREEN AND WALK THROUGH THE SCRIPT WITH THE ROOM.',
        readThroughConfirmTitle: 'START READ-THROUGH?',
        readThroughConfirmMessage: 'YOU\'LL HIT THE TELEPROMPTER. SHARE YOUR SCREEN SO EVERYONE CAN FOLLOW. ADVANCE THE SCRIPT AND END WHEN DONE.',
        readThroughBanner: 'READ-THROUGH MODE — SHARE YOUR SCREEN SO OTHERS CAN FOLLOW ALONG.',
      },
    },
    aiParameters: {
      slangRegistry: [
        'skibidi', 'sigma', 'rizz', 'gyatt', 'fanum tax', 'ohio',
        'based', 'cringe', 'sus', 'cap', 'no cap', 'fr',
      ],
      toneGuidelines: 'Maximum chaos, dopamine-driven, intentionally over-the-top, meme-dense',
      pacing: 'chaotic',
      archetypeLabels: {
        protagonist: 'The Chaos Agent',
        antagonist: 'The Wildcard',
        sidekick: 'The Sidekick',
        comic: 'The Meme Lord',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 100,
      hoverEffects: 'glow-pulse',
      clickFeedback: 'explode',
      soundEffects: ['explosion', 'whoosh', 'ding'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Impact" font-size="50" fill="#FF00FF" stroke="#00FFFF" stroke-width="1">SKITSO</text></svg>',
      typographyStyle: 'Impact',
      animations: {
        glitch: true,
        pulse: true,
        scanlines: true,
      },
    },
  },
  QUIET_STUDIO: {
    id: 'QUIET_STUDIO',
    visualTokens: {
      bgColor: '#FFFFFF',
      primaryColor: '#2C3E50',
      accentColor: '#7F8C8D',
      textColor: '#000000', // WCAG AA compliant (21:1 contrast on #FFFFFF)
      successColor: '#27AE60', // Muted green for success
      warningColor: '#E67E22', // Muted orange for warnings
      errorColor: '#E74C3C', // Muted red for errors
      infoColor: '#3498DB', // Muted blue for info
      headerFont: 'Helvetica Neue, sans-serif',
      bodyFont: 'Helvetica Neue, sans-serif',
      borderRadius: '2px',
      animationStyle: 'instant',
      cardStyle: {
        padding: '1.25rem',
        gap: '0.75rem',
        borderStyle: '1px solid #E0E0E0',
        shadowStyle: 'none',
      },
      spacing: {
        section: '2rem',
        component: '1rem',
        element: '0.5rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Submit',
        submitLoading: 'Generating...',
        cancel: 'Cancel',
        start: 'Start',
        startPerformance: 'Start Performance',
        join: 'Join',
        share: 'Share',
        next: 'Next',
        back: 'Back',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        goBack: 'Back',
        endScene: 'End Scene',
        exit: 'Exit',
        exportScript: 'Export Script',
        doAnother: 'Do Another',
        switchVibe: 'New Skit',
        wrapPartyExit: 'End Session',
      },
      placeholders: {
        theme: 'Theme (10-200 characters)',
        plot: 'Optional: extended plot details, beats, or constraints...',
        jokes: 'Optional: specific lines to incorporate (one per line)...',
        predefinedCharacterName: 'Character name',
        predefinedCharacterRole: 'Role (optional)',
        predefinedCharactersDescription:
          'Pre-define important characters here; the AI will create any remaining roles needed.',
        loadingCharactersBody: 'Generating balanced characters and archetypes...',
        loadingGeneratingBody: 'Generating script and visuals...',
        jokesCountLabel: 'custom lines',
        name: 'Name',
        sessionCode: 'Session code',
        search: 'Search',
      },
      errorMessages: {
        required: 'Required field',
        invalid: 'Invalid input',
        network: 'Connection error',
        generation: 'Generation failed',
        sessionLoadFailed: 'Unable to load this session. Please verify the link or code.',
        wrapPartyUnavailable: 'Wrap Party is unavailable. Rejoin the session to continue.',
      },
      successMessages: {
        saved: 'Saved',
        joined: 'Joined',
        shared: 'Shared',
        generated: 'Generated',
        wrapPartyReady: 'Performance complete. Time to reflect.',
      },
      sectionTitles: {
        vibeSelection: 'Select Style',
        configuration: 'Configuration',
        castingCouch: 'Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'Participants',
        characters: 'Characters',
        script: 'Script',
        performance: 'Performance',
        wrapParty: 'Completion',
        wrapPartySubtitle: 'Performance complete. Capture feedback and highlights.',
        wrapPartyNotReady: 'Completion screen will appear once the performance has finished.',
        wrapPartyDoAnotherConfirm: 'Do another with the same session?',
        wrapPartySwitchVibeConfirm: 'New skit with the same session?',
        wrapPartyExitConfirm: 'End session for everyone?',
        shareComingSoon: 'Share — Coming soon',
        wrapPartyRejoinToVote: 'Rejoin with your name to vote.',
        chatReactionsComingSoon: 'Quick chat & reactions — Coming soon',
        wrapPartyTopIndicator: '🌙',
        joinSessionTitle: 'Join Session',
        loadingSession: 'Loading session...',
        redirectingToStage: 'Redirecting to the stage...',
        redirectingToWrapParty: 'Redirecting to the wrap party...',
        actorWelcomeTitle: 'Welcome',
        lockedAssignmentIntro: 'Your character assignment is confirmed:',
        waitingForPerformance: 'Waiting for the director to begin.',
        waitingForGeneration: 'Waiting for the script and characters to finish generating.',
        // Director form labels
        themeLabel: 'Theme',
        plotLabel: 'Plot',
        toneLabel: 'Tone',
        participantsLabel: 'Participants',
        chaosLevelLabel: 'Chaos Level',
        jokesLabel: 'Jokes & Phrases',
        predefinedCharactersLabel: 'Pre-Defined Characters',
        // Loading titles
        loadingCharactersTitle: 'Generating Characters...',
        loadingContentTitle: 'Generating Content...',
        readThroughSubtext: 'Share your screen to walk through the script with others in the room.',
        readThroughConfirmTitle: 'Start read-through?',
        readThroughConfirmMessage: 'You\'ll go to the teleprompter. Share your screen so everyone can follow along. Advance the script and end when done.',
        readThroughBanner: 'Read-through mode — share your screen so others can follow along.',
        endSceneConfirm: 'End Scene?',
        endSceneConfirmMessage: 'This will end the performance and move everyone to the completion screen.',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Professional, minimalist, anti-cringe, clean, productivity-focused',
      pacing: 'measured',
      archetypeLabels: {
        protagonist: 'The Narrator',
        antagonist: 'The Observer',
        sidekick: 'The Assistant',
        comic: 'The Commentator',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 0,
      hoverEffects: 'none',
      clickFeedback: 'minimal',
      soundEffects: [],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Helvetica Neue" font-size="40" fill="#2C3E50" font-weight="300">SKITSO</text></svg>',
      typographyStyle: 'Helvetica Neue Light',
      animations: {
        glitch: false,
        pulse: false,
        scanlines: false,
      },
    },
  },
};
