/**
 * VibeContext Configuration Objects
 * 
 * Complete configuration for all five production styles, including
 * visual tokens, linguistic tone, AI parameters, and interaction patterns.
 */

import type { VibeContext } from '../types/vibe';

export const VIBE_CONFIGS: Record<string, VibeContext> = {
  VIRAL_NEON: {
    id: 'VIRAL_NEON',
    visualTokens: {
      bgColor: '#0A0A0A',
      primaryColor: '#8AFB17',
      accentColor: '#BF40BF',
      textColor: '#FFFFFF', // WCAG AA compliant (21:1 contrast on #0A0A0A)
      headerFont: 'Inter Black Italic, sans-serif',
      bodyFont: 'Inter, sans-serif',
      borderRadius: '4px',
      animationStyle: 'snappy',
      cardStyle: {
        padding: '1.5rem',
        gap: '1rem',
        borderStyle: '2px solid var(--color-primary)',
        shadowStyle: '0 0 20px rgba(138, 251, 23, 0.3)',
      },
      spacing: {
        section: '3rem',
        component: '2rem',
        element: '1rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Send It',
        cancel: 'Nah',
        start: 'Let\'s Go',
        startPerformance: 'Start the Show',
        join: 'Hop In',
        share: 'Drop Link',
        next: 'Next',
        back: 'Back',
        save: 'Lock It',
        edit: 'Fix It',
        delete: 'Yeet',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        exit: 'Exit',
      },
      placeholders: {
        theme: 'What\'s the vibe? (10-200 chars)',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'This is required, no cap',
        invalid: 'That ain\'t it, chief',
        network: 'Connection failed, try again',
        generation: 'AI had a moment, retry?',
      },
      successMessages: {
        saved: 'Locked in!',
        joined: 'You\'re in!',
        shared: 'Link dropped!',
        generated: 'It\'s ready!',
      },
      sectionTitles: {
        vibeSelection: 'Pick Your Vibe',
        configuration: 'The Vibe',
        castingCouch: 'The Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'The Squad',
        characters: 'The Cast',
        script: 'The Script',
        performance: 'The Stage',
        wrapParty: 'The Wrap',
      },
    },
    aiParameters: {
      slangRegistry: [
        'no cap', 'fr fr', 'it\'s giving', 'slay', 'ate', 'period',
        'bestie', 'main character', 'vibe check', 'that\'s fire',
        'lowkey', 'highkey', 'bet', 'say less', 'facts', 'deadass',
      ],
      toneGuidelines: 'High-energy, meme-dense, chaotic, fast-paced dialogue with 2026 slang',
      pacing: 'snappy',
      archetypeLabels: {
        protagonist: 'The Main Character',
        antagonist: 'The Villain',
        sidekick: 'The Sidekick',
        comic: 'The Comedian',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 200,
      hoverEffects: 'glow',
      clickFeedback: 'pulse',
      soundEffects: ['click', 'whoosh'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Inter Black Italic" font-size="48" fill="#8AFB17" stroke="#BF40BF" stroke-width="0.5">SKITSO</text></svg>',
      typographyStyle: 'Inter Black Italic',
      animations: {
        glitch: true,
        pulse: true,
        scanlines: true,
      },
    },
  },
  INDIE_A24: {
    id: 'INDIE_A24',
    visualTokens: {
      bgColor: '#141414',
      primaryColor: '#CC7722',
      accentColor: '#FFFFFF',
      textColor: '#FFFFFF', // WCAG AA compliant (15.8:1 contrast on #141414)
      headerFont: 'EB Garamond, serif',
      bodyFont: 'Roboto Mono, monospace',
      borderRadius: '0px',
      animationStyle: 'slow-fade',
      cardStyle: {
        padding: '2rem',
        gap: '1.5rem',
        borderStyle: '1px solid rgba(204, 119, 34, 0.3)',
        shadowStyle: 'none',
      },
      spacing: {
        section: '4rem',
        component: '2.5rem',
        element: '1.25rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Submit',
        cancel: 'Cancel',
        start: 'Begin',
        startPerformance: 'Begin Performance',
        join: 'Join',
        share: 'Share',
        next: 'Next',
        back: 'Back',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        exit: 'Exit',
      },
      placeholders: {
        theme: 'Enter theme (10-200 characters)',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'This field is required',
        invalid: 'Invalid input',
        network: 'Connection error, please retry',
        generation: 'Generation failed, please retry',
      },
      successMessages: {
        saved: 'Saved',
        joined: 'Joined successfully',
        shared: 'Shared',
        generated: 'Generated',
      },
      sectionTitles: {
        vibeSelection: 'Select Production Style',
        configuration: 'Genre Selection',
        castingCouch: 'Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'Cast',
        characters: 'Characters',
        script: 'Script',
        performance: 'Performance',
        wrapParty: 'Wrap Party',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Cinematic, award-winning dialogue, contemplative, meaningful',
      pacing: 'contemplative',
      archetypeLabels: {
        protagonist: 'The Protagonist',
        antagonist: 'The Antagonist',
        sidekick: 'The Companion',
        comic: 'The Wit',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 500,
      hoverEffects: 'fade',
      clickFeedback: 'subtle',
      soundEffects: [],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="EB Garamond" font-size="42" fill="#CC7722" font-style="italic">SKITSO</text></svg>',
      typographyStyle: 'EB Garamond Italic',
      animations: {
        glitch: false,
        pulse: false,
        scanlines: false,
      },
    },
  },
  SITCOM_STUDIO: {
    id: 'SITCOM_STUDIO',
    visualTokens: {
      bgColor: '#F5F5F5',
      primaryColor: '#FF6B35',
      accentColor: '#004E89',
      textColor: '#000000', // WCAG AA compliant (18.1:1 contrast on #F5F5F5)
      headerFont: 'Comic Sans MS, cursive',
      bodyFont: 'Arial, sans-serif',
      borderRadius: '12px',
      animationStyle: 'bouncy',
      cardStyle: {
        padding: '1.5rem',
        gap: '1rem',
        borderStyle: '3px solid var(--color-primary)',
        shadowStyle: '0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      spacing: {
        section: '2.5rem',
        component: '1.5rem',
        element: '0.75rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Let\'s Do This!',
        cancel: 'Never Mind',
        start: 'Action!',
        startPerformance: 'Lights, Camera, Action!',
        join: 'Join the Fun!',
        share: 'Share with Friends',
        next: 'Next →',
        back: '← Back',
        save: 'Save It',
        edit: 'Change It',
        delete: 'Remove',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        exit: 'Exit',
      },
      placeholders: {
        theme: 'What\'s the story? (10-200 chars)',
        name: 'Your name',
        sessionCode: 'Enter session code',
        search: 'Search...',
      },
      errorMessages: {
        required: 'Oops! This is required',
        invalid: 'Hmm, that doesn\'t look right',
        network: 'Connection hiccup, try again',
        generation: 'Something went wrong, retry?',
      },
      successMessages: {
        saved: 'All set!',
        joined: 'Welcome!',
        shared: 'Shared!',
        generated: 'Ready to go!',
      },
      sectionTitles: {
        vibeSelection: 'Choose Your Style',
        configuration: 'The Setup',
        castingCouch: 'The Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'The Cast',
        characters: 'Characters',
        script: 'The Script',
        performance: 'Lights, Camera, Action!',
        wrapParty: 'That\'s a Wrap!',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Nostalgic, high-energy, comedic, TV sitcom style',
      pacing: 'energetic',
      archetypeLabels: {
        protagonist: 'The Lead',
        antagonist: 'The Foil',
        sidekick: 'The Best Friend',
        comic: 'The Jokester',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 300,
      hoverEffects: 'bounce',
      clickFeedback: 'bounce',
      soundEffects: ['laugh', 'applause'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Comic Sans MS" font-size="44" fill="#FF6B35">SKITSO</text></svg>',
      typographyStyle: 'Comic Sans MS',
      animations: {
        glitch: false,
        pulse: true,
        scanlines: false,
      },
    },
  },
  BRAINROT_THEATER: {
    id: 'BRAINROT_THEATER',
    visualTokens: {
      bgColor: '#000000',
      primaryColor: '#FF00FF',
      accentColor: '#00FFFF',
      textColor: '#FFFFFF', // WCAG AA compliant (21:1 contrast on #000000)
      headerFont: 'Impact, sans-serif',
      bodyFont: 'Arial Black, sans-serif',
      borderRadius: '20px',
      animationStyle: 'bouncy',
      cardStyle: {
        padding: '2rem',
        gap: '1.5rem',
        borderStyle: '4px dashed var(--color-primary)',
        shadowStyle: '0 0 30px rgba(255, 0, 255, 0.5), 0 0 60px rgba(0, 255, 255, 0.3)',
      },
      spacing: {
        section: '2rem',
        component: '1.5rem',
        element: '1rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'SEND IT!!!',
        cancel: 'NOPE',
        start: 'CHAOS MODE',
        startPerformance: 'START THE CHAOS!!!',
        join: 'JOIN THE CHAOS',
        share: 'SPREAD IT',
        next: 'NEXT →→→',
        back: '←←← BACK',
        save: 'LOCK IT IN',
        edit: 'FIX IT NOW',
        delete: 'DELETE FOREVER',
        pause: 'PAUSE',
        resume: 'RESUME',
        advance: 'ADVANCE',
        exit: 'EXIT',
      },
      placeholders: {
        theme: 'WHAT\'S THE CHAOS? (10-200 CHARS)',
        name: 'YOUR NAME',
        sessionCode: 'ENTER CODE',
        search: 'SEARCH...',
      },
      errorMessages: {
        required: 'YOU NEED THIS!!!',
        invalid: 'WRONG!!!',
        network: 'CONNECTION BROKE, RETRY?',
        generation: 'AI BROKE, RETRY?',
      },
      successMessages: {
        saved: 'LOCKED!!!',
        joined: 'YOU\'RE IN!!!',
        shared: 'SPREAD!!!',
        generated: 'READY!!!',
      },
      sectionTitles: {
        vibeSelection: 'PICK YOUR CHAOS',
        configuration: 'THE CHAOS',
        castingCouch: 'THE CASTING COUCH',
        characterDossier: 'CHARACTER DOSSIER',
        personalityTraits: 'PERSONALITY TRAITS',
        attributes: 'ATTRIBUTES',
        hiddenMotivation: 'HIDDEN MOTIVATION',
        participants: 'THE SQUAD',
        characters: 'THE CAST',
        script: 'THE SCRIPT',
        performance: 'THE STAGE',
        wrapParty: 'THE WRAP',
      },
    },
    aiParameters: {
      slangRegistry: [
        'skibidi', 'sigma', 'rizz', 'gyatt', 'fanum tax', 'ohio',
        'based', 'cringe', 'sus', 'cap', 'no cap', 'fr',
      ],
      toneGuidelines: 'Maximum chaos, dopamine-driven, intentionally over-the-top, meme-dense',
      pacing: 'chaotic',
      archetypeLabels: {
        protagonist: 'The Chaos Agent',
        antagonist: 'The Wildcard',
        sidekick: 'The Sidekick',
        comic: 'The Meme Lord',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 100,
      hoverEffects: 'glow-pulse',
      clickFeedback: 'explode',
      soundEffects: ['explosion', 'whoosh', 'ding'],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Impact" font-size="50" fill="#FF00FF" stroke="#00FFFF" stroke-width="1">SKITSO</text></svg>',
      typographyStyle: 'Impact',
      animations: {
        glitch: true,
        pulse: true,
        scanlines: true,
      },
    },
  },
  QUIET_STUDIO: {
    id: 'QUIET_STUDIO',
    visualTokens: {
      bgColor: '#FFFFFF',
      primaryColor: '#2C3E50',
      accentColor: '#7F8C8D',
      textColor: '#000000', // WCAG AA compliant (21:1 contrast on #FFFFFF)
      headerFont: 'Helvetica Neue, sans-serif',
      bodyFont: 'Helvetica Neue, sans-serif',
      borderRadius: '2px',
      animationStyle: 'instant',
      cardStyle: {
        padding: '1.25rem',
        gap: '0.75rem',
        borderStyle: '1px solid #E0E0E0',
        shadowStyle: 'none',
      },
      spacing: {
        section: '2rem',
        component: '1rem',
        element: '0.5rem',
      },
    },
    linguisticTone: {
      buttonLabels: {
        submit: 'Submit',
        cancel: 'Cancel',
        start: 'Start',
        startPerformance: 'Start Performance',
        join: 'Join',
        share: 'Share',
        next: 'Next',
        back: 'Back',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        pause: 'Pause',
        resume: 'Resume',
        advance: 'Advance',
        exit: 'Exit',
      },
      placeholders: {
        theme: 'Theme (10-200 characters)',
        name: 'Name',
        sessionCode: 'Session code',
        search: 'Search',
      },
      errorMessages: {
        required: 'Required field',
        invalid: 'Invalid input',
        network: 'Connection error',
        generation: 'Generation failed',
      },
      successMessages: {
        saved: 'Saved',
        joined: 'Joined',
        shared: 'Shared',
        generated: 'Generated',
      },
      sectionTitles: {
        vibeSelection: 'Select Style',
        configuration: 'Configuration',
        castingCouch: 'Casting Couch',
        characterDossier: 'Character Dossier',
        personalityTraits: 'Personality Traits',
        attributes: 'Attributes',
        hiddenMotivation: 'Hidden Motivation',
        participants: 'Participants',
        characters: 'Characters',
        script: 'Script',
        performance: 'Performance',
        wrapParty: 'Completion',
      },
    },
    aiParameters: {
      slangRegistry: [],
      toneGuidelines: 'Professional, minimalist, anti-cringe, clean, productivity-focused',
      pacing: 'measured',
      archetypeLabels: {
        protagonist: 'The Narrator',
        antagonist: 'The Observer',
        sidekick: 'The Assistant',
        comic: 'The Commentator',
        narrator: 'The Narrator',
      },
    },
    interactionPatterns: {
      animationSpeed: 0,
      hoverEffects: 'none',
      clickFeedback: 'minimal',
      soundEffects: [],
    },
    logo: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 60"><text x="10" y="40" font-family="Helvetica Neue" font-size="40" fill="#2C3E50" font-weight="300">SKITSO</text></svg>',
      typographyStyle: 'Helvetica Neue Light',
      animations: {
        glitch: false,
        pulse: false,
        scanlines: false,
      },
    },
  },
};
